/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.uwpr.www.data;

import java.net.URL;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.uwpr.data.DataURI;
import org.uwpr.data.DataURIFactory;
import org.uwpr.data.DataURISaver;
import org.uwpr.htpasswd.HTAccessFileUtils;
import org.yeastrc.project.Project;
import org.yeastrc.project.ProjectFactory;
import org.yeastrc.www.user.User;
import org.yeastrc.www.user.UserUtils;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="Failure" path="/viewProject.do"
 * @struts.action-forward name="Success" path="/viewProject.do" redirect="true"
 */
public class UpdateDataURIAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		
		// User making this request
		User user = UserUtils.getUser(request);
		if (user == null) {
			ActionErrors errors = new ActionErrors();
			errors.add("username", new ActionMessage("error.login.notloggedin"));
			saveErrors( request, errors );
			return mapping.findForward("authenticate");
		}

		Project project = null;
		int projectID = ((UpdateDataURIForm)(form)).getProjectID();
		int dataID = ((UpdateDataURIForm)form).getDataID();
		String uri = ((UpdateDataURIForm)(form)).getUri();
		String comments = ((UpdateDataURIForm)(form)).getComments();
		
		try {
			project = ProjectFactory.getProject( projectID );
		} catch (Exception e) { ; }
		
		// could not load the project specified
		if (project == null) {
			ActionErrors errors = new ActionErrors();
			errors.add("upload", new ActionMessage("error.upload.invalid.project"));
			saveErrors( request, errors );
			
			ActionForward af = mapping.findForward( "Failure" ) ;
			af = new ActionForward( af.getPath() + "?ID=" + project.getID(), af.getRedirect() ) ;
			return af ;
		}

		// this user doesn't have access to modify this project
		if (!project.checkAccess( user.getResearcher() ) ) {
			ActionErrors errors = new ActionErrors();
			errors.add("upload", new ActionMessage("error.upload.access.denied"));
			saveErrors( request, errors );

			ActionForward af = mapping.findForward( "Failure" ) ;
			af = new ActionForward( af.getPath() + "?ID=" + project.getID(), af.getRedirect() ) ;
			return af ;
		}
		
		if (uri == null || uri.equals( "" )) {
			ActionErrors errors = new ActionErrors();
			errors.add("upload", new ActionMessage("error.upload.no.uri"));
			saveErrors( request, errors );

			ActionForward af = mapping.findForward( "Failure" ) ;
			af = new ActionForward( af.getPath() + "?ID=" + project.getID(), af.getRedirect() ) ;
			return af ;
		}

		DataURI dataURI = DataURIFactory.getInstance().getDataURI(dataID);
		if (dataURI == null) {
			ActionErrors errors = new ActionErrors();
			errors.add("upload", new ActionMessage("error.upload.no.data.uri"));
			saveErrors( request, errors );

			ActionForward af = mapping.findForward( "Failure" ) ;
			af = new ActionForward( af.getPath() + "?ID=" + project.getID(), af.getRedirect() ) ;
			return af ;
		}
		
		dataURI.setUri( uri );
		dataURI.setComments( comments );
		
		try {
			DataURISaver.getInstance().save( dataURI );
			HTAccessFileUtils.getInstance().writeHTAccessFile(project, new URL( uri ) );
		} catch (Exception e) { ; }
		
		// we had difficulty saving this to the database
		if (dataURI.getId() == 0) {
			ActionErrors errors = new ActionErrors();
			errors.add("upload", new ActionMessage("error.upload.save.error"));
			saveErrors( request, errors );
			
			ActionForward af = mapping.findForward( "Failure" ) ;
			af = new ActionForward( af.getPath() + "?ID=" + project.getID(), af.getRedirect() ) ;
			return af ;
		}
		
		ActionForward af = mapping.findForward( "Success" ) ;
		af = new ActionForward( af.getPath() + "?ID=" + project.getID(), af.getRedirect() ) ;
		return af ;
	}
}