/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.uwpr.www.data;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2008
 * 
 * XDoclet definition:
 * @struts.form name="updateExternalDataLinkForm"
 */
public class UpdateDataURIForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** comments property */
	private String comments;

	/** projectID property */
	private int projectID;

	/** uri property */
	private String uri;

	/** dataID property */
	private int dataID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		
		ActionErrors errors = new ActionErrors();
		if (this.getUri() == null || this.getUri().equals( "" ) ) {
			errors.add("data", new ActionMessage("error.upload.external.data.noURI"));
		}

		return errors;
	}

	/** 
	 * Returns the comments.
	 * @return String
	 */
	public String getComments() {
		return comments;
	}

	/** 
	 * Set the comments.
	 * @param comments The comments to set
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/** 
	 * Returns the projectID.
	 * @return int
	 */
	public int getProjectID() {
		return projectID;
	}

	/** 
	 * Set the projectID.
	 * @param projectID The projectID to set
	 */
	public void setProjectID(int projectID) {
		this.projectID = projectID;
	}

	/** 
	 * Returns the uri.
	 * @return String
	 */
	public String getUri() {
		return uri;
	}

	/** 
	 * Set the uri.
	 * @param uri The uri to set
	 */
	public void setUri(String uri) {
		this.uri = uri;
	}

	/** 
	 * Returns the dataID.
	 * @return int
	 */
	public int getDataID() {
		return dataID;
	}

	/** 
	 * Set the dataID.
	 * @param dataID The dataID to set
	 */
	public void setDataID(int dataID) {
		this.dataID = dataID;
	}
}